collections:
  robots:
    output: true
  
  
  forms:
    output: true

  committees:
    output: true
    permalink: /committee/:title


defaults:
  -
    scope:
      path: "_robots" # Empty string represents all files
    values:
      published: false
      layout: robot
      permalink: "/robots/:title"

  -
    scope:
      path: ""
    values:
      bg: light
      txt: dark

  -
    scope:
      path: "_forms"
    values:
      layout: gForm
      bg: light
      txt: dark
  -
    scope:
      path: "_posts" # Empty string represents all files
    values:
      permalink: "/posts/:year/:title"
      published: false
      layout: post
      bg: light
      txt: dark



plugins:
  - "jekyll-github-metadata"
  - "jekyll-env"
  - jekyll-include-cache

exclude: ['Archive', 'Documentation', 'node_modules', 'tina']

repository: Operation-P-E-A-C-C-E-Robotics/Operation-P-E-A-C-C-E-Robotics.github.io


banner:
  image-url: "/assets/images/original-banner.jpg"
  image-align: "top"
  header: "Operation PEACCE Robotics"
  subheader: "Practicing Engineering and Competitive Cooperative Excellence"

#set alert banners to be shown on the 
alerts:
  # - header: Test
  #   message: This is a test
  #   class: success
  # Color Classes
  # primary: blue
  # success: green
  # info: teal blue
  # warning: yellow
  # danger: red
  # secondary: grey
  # dark: dark grey
  # light: light grey

  # - header: "Next Event: Open House"
  #   message: Please join us for an Open House on Saturday June 3rd from 1pm-5pm
  #   class: secondary
  
