collections:
  robots:
    output: true

  admin:
    output: true


plugins:
  - "jekyll-github-metadata"
  - "jekyll-env"


exclude: ['Archive', 'Documentation']

repository: Operation-P-E-A-C-C-E-Robotics/Operation-P-E-A-C-C-E-Robotics.github.io


banner:
  image-url: "/assets/images/original-banner.jpg"
  image-align: "top"
  header: "Operation PEACCE Robotics"
  subheader: "Practicing Engineering and Competitive Cooperative Excellence"

#set alert banners to be shown on the 
alerts:
  # - header: Test
  #   message: This is a test
  #   class: success
  
