collections:
  robots:
    output: true




defaults:
  -
    scope:
      path: "_robots" # Empty string represents all files
    values:
      published: true
      layout: robot

plugins:
  - "jekyll-github-metadata"
  - "jekyll-env"
  - jekyll-include-cache

exclude: ['Archive', 'Documentation']

repository: Operation-P-E-A-C-C-E-Robotics/Operation-P-E-A-C-C-E-Robotics.github.io


banner:
  image-url: "/assets/images/original-banner.jpg"
  image-align: "top"
  header: "Operation PEACCE Robotics"
  subheader: "Practicing Engineering and Competitive Cooperative Excellence"

#set alert banners to be shown on the 
alerts:
  # - header: Test
  #   message: This is a test
  #   class: success
  
