---
title: Operation P E A C C E Robotics.Github.Io
timezone: UTC
collections:
  admin:
    title: Admin
    output: true
  posts:
    title: Posts
    output: true
  robots:
    title: Robots
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-github-metadata
- jekyll-env
exclude:
- Archive
- Documentation
repository: Operation-P-E-A-C-C-E-Robotics/Operation-P-E-A-C-C-E-Robotics.github.io
banner:
  image-url: "/assets/images/original-banner.jpg"
  image-align: top
  header: Operation PEACCE Robotics
  subheader: Practicing Engineering and Competitive Cooperative Excellence
alerts: 
