backend:
  name: git-gateway
  repo: Operation-P-E-A-C-C-E-Robotics/Operation-P-E-A-C-C-E-Robotics.github.io
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "File Name", name: "filename", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "robots" # Used in routes, e.g., /admin/collections/blog
    label: "Robot Profiles" # Used in the UI
    folder: "_robots/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "robot"}
      - {label: "Year", name: "year", widget: "integer"}
      - {label: "Robot Name", name: "author", widget: "string"}
      - {label: "Game Name", name: "game", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "string"}
      - {label: "Technical Binder", name: "techBinder", widget: "string"}
      - {label: "Youtube Playlist", name: "matchVideoPlaylist", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}