name: Check for active TBA events daily

on:
    schedule:
        - cron: '0 11 * * *'  # Runs daily at 11:00 UTC (06:00 ET or 07:00 EDT).
    workflow_dispatch:

jobs:
    check-tba-event:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v7
              with:
                sparse-checkout: |
                  checkActiveComps.py
                  data/tba
                sparse-checkout-cone-mode: true

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: pip install requests

            - name: Check for active TBA events
              run: python checkActiveComps.py
              env:
                  TBA_API_KEY: ${{ secrets.TBA_API_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}