name: Pull Google Calendar Events

on:
  push:
    branches: [ google-api-backend ]

  schedule:
    - cron: '0 0 * * *'  # runs every day at midnight

jobs:
  pull_events:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # - name: Install Google API Client
    #   run: pip install google-api-python-client

    - name: Run Script
      env:
        API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
      run: python pull-events.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add events.json
        git commit -m "Update events.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
