on: [push]

name: Save data from The Blue Alliance to local file

jobs:
  Execute-Python-Script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install python dependencies
        run: |
          pip install -r requirements.txt
      - name: execute python script # run the run.py to get the latest data
        run: |
          python tba.py
        env:
          TBA_API_KEY: ${{ secrets.tba_api_key }} # if run.py requires passwords..etc, set it as secrets
