name: Trigger update workflows on all branches 
on: 
  schedule: 
   - cron: '35 15 * * *' #run At 15:35hrs UTC (10:35hrs EST) 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  trigger-tba-all-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: tba-all
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: updateAllYears.yml
    
  trigger-tba-current-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: tba-cur
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: updateCurrentYear.yml

  trigger-google-calendar-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: calendar
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: calendarPYRunner.yml
        