name: Trigger update workflows on all branches
on:
  schedule:
    - cron: '35 10 * * *' # Run at 5:35 AM EST | 10:35 AM UTC (Github Actions runs on UTC, no Daylight Savings Time changes are accounted for in this trigger)
    - cron: '*/5 * * 3-4 *' # Run at every 5th minute in every month from March through April to update data from The Blue Alliance for the current season during competitions.

  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check cron trigger
        id: cron_check
        run: | 
          echo "Cron trigger: ${{ github.event_name }}"

      - name: Trigger TBA workflows
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '35 10 * * *' || github.event_name == 'workflow_dispatch'}}
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: gh-actions-tba-data-backend
          workflow: 56043978

      - name: Trigger TBA current workflow
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '*/5 * * 3-4 *' || github.event_name == 'workflow_dispatch' || github.event_name == 'issues' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: gh-actions-tba-data-backend
          workflow: 56043979

      - name: Trigger Google Calendar workflow
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '35 10 * * *' || github.event_name == 'workflow_dispatch' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: google-api-backend
          workflow: 57165542


      - name: Close Issue
        if: ${{github.event_name == 'issues'}}
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Auto-closing issue

