name: Trigger update workflows on all branches
on:
  schedule:
    - cron: '35 10 * * *' # Run at 5:35 AM EST | 10:35 AM UTC (Github Actions runs on UTC, no Daylight Savings Time changes are accounted for in this trigger)
    - cron: '*/5 * * 3-4 *' # Run at every 5th minute in every month from March through April to update data from The Blue Alliance for the current season during competitions.

  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check cron trigger
        id: cron_check
        run: | 
          echo "Cron trigger: ${{ github.event_name }}"

      - name: Trigger TBA workflows
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '35 10 * * *' || github.event_name == 'workflow_dispatch'}}
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: gh-actions-tba-data-backend
          workflow: 56043978

      - name: Trigger TBA current workflow
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '*/5 * * 3-4 *' || github.event_name == 'workflow_dispatch' || github.event_name == 'issues' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: gh-actions-tba-data-backend
          workflow: 56043979

      - name: Trigger Google Calendar workflow
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '35 10 * * *' || github.event_name == 'workflow_dispatch' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: google-api-backend
          workflow: 57165542

  close-issue-with-comment:
    runs-on: ubuntu-latest 
    steps:
      - name: Comment on Issue
        uses: actions/github-rest-api@v3
        if: ${{github.event_name == 'issues'}}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          endpoint: issues/create-comment
          method: POST
          body: |
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.repository }}",
              "issue_number": ${{ github.event.issue.number }},
              "body": "Github Actions was succesfully triggered, Closing."
            }

      - name: Close Issue
        uses: actions/github-rest-api@v3
        if: ${{github.event_name == 'issues'}}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          endpoint: issues/update
          method: PATCH
          body: |
            {
              "owner": "${{ github.repository_owner }}",
              "repo": "${{ github.repository }}",
              "issue_number": ${{ github.event.issue.number }},
              "state": "closed"
            }